name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      - name: Check AWS env vars
        run: |
          echo "AWS_ACCESS_KEY_ID     = '$AWS_ACCESS_KEY_ID'"
          echo "AWS_SECRET_ACCESS_KEY = '$AWS_SECRET_ACCESS_KEY'"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://health-being-web --delete
          aws cloudfront create-invalidation --distribution-id ABCDEFGHIJKL --paths "/*"
